# @package _group_
env: "pets_reacher"
envs:
  -
    env_name: "pets_reacher"
    wrappers: []
    task_name: "task_0"
    reward_fn: "pets_reacher"
    reward_fn_kwargs:
      task_index: 0
    env_kwargs:
      task_id: 0
      hide_goal: true
  -
    env_name: "pets_reacher"
    wrappers: []
    task_name: "task_1"
    reward_fn: "pets_reacher"
    reward_fn_kwargs:
      task_index: 1
    env_kwargs:
      task_id: 1
      hide_goal: true
  -
    env_name: "pets_reacher"
    wrappers: []
    task_name: "task_2"
    reward_fn: "pets_reacher"
    reward_fn_kwargs:
      task_index: 2
    env_kwargs:
      task_id: 2
      hide_goal: true
  -
    env_name: "pets_reacher"
    wrappers: []
    task_name: "task_3"
    reward_fn: "pets_reacher"
    reward_fn_kwargs:
      task_index: 3
    env_kwargs:
      task_id: 3
      hide_goal: true
  -
    env_name: "pets_reacher"
    wrappers: []
    task_name: "task_4"
    reward_fn: "pets_reacher"
    reward_fn_kwargs:
      task_index: 4
    env_kwargs:
      task_id: 4
      hide_goal: true
  -
    env_name: "pets_reacher"
    wrappers: []
    task_name: "task_5"
    reward_fn: "pets_reacher"
    reward_fn_kwargs:
      task_index: 5
    env_kwargs:
      task_id: 5
      hide_goal: true
  -
    env_name: "pets_reacher"
    wrappers: []
    task_name: "task_6"
    reward_fn: "pets_reacher"
    reward_fn_kwargs:
      task_index: 6
    env_kwargs:
      task_id: 6
      hide_goal: true
  -
    env_name: "pets_reacher"
    wrappers: []
    task_name: "task_7"
    reward_fn: "pets_reacher"
    reward_fn_kwargs:
      task_index: 7
    env_kwargs:
      task_id: 7
      hide_goal: true
  -
    env_name: "pets_reacher"
    wrappers: []
    task_name: "task_8"
    reward_fn: "pets_reacher"
    reward_fn_kwargs:
      task_index: 8
    env_kwargs:
      task_id: 8
      hide_goal: true
  -
    env_name: "pets_reacher"
    wrappers: []
    task_name: "task_9"
    reward_fn: "pets_reacher"
    reward_fn_kwargs:
      task_index: 9
    env_kwargs:
      task_id: 9
      hide_goal: true

term_fn: "no_termination"
policy_to_use: "COMBINED"
learned_rewards: false
reward_fn: "reacher"
num_steps: 15000
trial_length: 150  # 1000
epoch_length: 150

num_elites: 5
model_lr: 0.00075  # 4e-4
model_wd: 0  # 1.7e-4
model_batch_size: 32
validation_ratio: 0.  # 0.05
no_delta_list: []  # [7, 8, 9]  # [ 0 ]
freq_train_model: 150  # 250
patience: 5  # 25
num_epochs_train_model: 5  # 25

planning_horizon: 15
cem_num_iters: 5
cem_elite_ratio: 0.1
cem_population_size: 400  # 350
cem_alpha: 0.1

# Dynamics model config
observe_task_id: false
forward_postprocess_fn:
  _target_: mbrl.env.pets_reacher

# MBPO Config
effective_model_rollouts_per_step: 400
rollout_schedule: [20, 150, 1, 1]
num_sac_updates_per_step: 40
sac_updates_every_steps: 1
num_epochs_to_retain_sac_buffer: 1

sac_batch_size: 256
sac_alpha_lr: 0.0003
sac_actor_lr: 0.0003
sac_actor_update_frequency: 4
sac_critic_lr: 0.00003
sac_critic_target_update_frequency: 4
sac_target_entropy: -3
sac_hidden_depth: 2
sac_hidden_dim: 256

# Switching mechanism config
# in ["last_n_episodes", "current_observation"]
returns_expectation_calculation_method: "current_observation"
returns_expectation_n_episodes: 3

planning_mopo_penalty_coeff: 0
