# @package _group_
policy_to_use: "EXPLICIT_POLICY"
env: "pets_halfcheetah"
num_distinct_envs: 3
envs:
  -
    env_name: "pets_halfcheetah"
    wrappers: []
    task_name: "forward"
    reward_fn: "pets_halfcheetah"
  -
    env_name: "pets_halfcheetah"
    wrappers:
      -
        _target_: mbrl.env.wrappers.HalfCheetahBackwardsWrapper
    task_name: "backwards"
    reward_fn: "pets_halfcheetah_backwards"
  -
    env_name: "pets_halfcheetah"
    wrappers:
      -
        _target_: mbrl.env.wrappers.JumpWrapper
    task_name: "jump"
    reward_fn: "pets_halfcheetah_jump"
  -
    env_name: "pets_halfcheetah"
    wrappers: []
    task_name: "forward"
    reward_fn: "pets_halfcheetah"
  -
    env_name: "pets_halfcheetah"
    wrappers:
      - _target_: mbrl.env.wrappers.HalfCheetahBackwardsWrapper
    task_name: "backwards"
    reward_fn: "pets_halfcheetah_backwards"
  -
    env_name: "pets_halfcheetah"
    wrappers:
      - _target_: mbrl.env.wrappers.JumpWrapper
    task_name: "jump"
    reward_fn: "pets_halfcheetah_jump"
  
term_fn: "no_termination"
obs_process_fn: mbrl.env.pets_halfcheetah.HalfCheetahEnv.preprocess_fn
learned_rewards: false
num_steps: 150000
trial_length: 1000
epoch_length: 1000

num_elites: 5
model_lr: 0.001  # 2e-4
model_wd: 0.00002
model_batch_size: 256
validation_ratio: 0.  # 0.2
no_delta_list: [ 0 ]
freq_train_model: 250
effective_model_rollouts_per_step: 400
rollout_schedule: [20, 150, 1, 1]
num_sac_updates_per_step: 40
sac_updates_every_steps: 1
num_epochs_to_retain_sac_buffer: 1
patience: 5  # 1
num_epochs_train_model: 5  # 25

sac_alpha_lr: 0.0003
sac_actor_lr: 0.0003
sac_actor_update_frequency: 4
sac_critic_lr: 0.00003
sac_critic_target_update_frequency: 4
sac_target_entropy: -3
sac_hidden_depth: 2
sac_hidden_dim: 1024
sac_batch_size: 256

planning_horizon: 30
cem_num_iters: 5
cem_elite_ratio: 0.1
cem_population_size: 500  # 350
cem_alpha: 0.1

# Dynamics model config
observe_task_id: true
forward_postprocess_fn: None

planning_mopo_penalty_coeff: 0
policy_mopo_penalty_coeff: 0
