# @package _group_
env: "pets_reacher"
envs:
  -
    env_name: "pets_reacher"
    wrappers: []
    task_name: "forward"
    reward_fn: "pets_reacher"

learned_rewards: false
reward_fn: "reacher"
num_steps: 15000
trial_length: 150  # 1000

num_elites: 5
model_lr: 0.00075  # 4e-4
model_wd: 0  # 1.7e-4
model_batch_size: 32
validation_ratio: 0.  # 0.05
no_delta_list: [7, 8, 9]  # [ 0 ]
freq_train_model: 150  # 250
patience: 5  # 25
num_epochs_train_model: 5  # 25

planning_horizon: 15
cem_num_iters: 5
cem_elite_ratio: 0.1
cem_population_size: 400  # 350
cem_alpha: 0.1

# Dynamics model config
observe_task_id: true
forward_postprocess_fn:
  _target_: mbrl.env.pets_reacher
